### ISSUE TITLE
add new F type = 4 model

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/ss-test-models#10]
F type 4 was just added into main, so it would be useful to convert an existing model to use F method 4 in the test set. In theory, I think a model with multiple fleets and some high F values would be a good one to convert (@Rick-Methot-NOAA feel free to provide more guidance on a useful model)

**Comment by Rick-Methot-NOAA** [comment]
Let's convert vermilion with this setup:

4 # F_Method:  1=Pope; 2=instan. F; 3=hybrid; 4=fleet-specific parm/hybrid
(#4 is recommended)
3 # max F or harvest rate, depends on F_Method
# for Fmethod 1; no additional F input needed
# for Fmethod=2; read overall start F value; overall phase; N detailed
inputs to read
# for Fmethod=3; read N iterations for tuning for Fmethod 3
# for Fmethod=4; read list of fleets needing parameters; syntax is:  fleet,
F_starting_value (if start_PH=1), first PH for parms (99 to stay in hybrid)
# for Fmethod=4; then read N tuning loops for hybrid fleets 2-3 normally
enough
#Fleet start_F first_parm_phase
 1 0.05 4
 2 0.05 4
 3 0.1 4
 4 0.04 1
 -999 1 1
3 #_number of tuning loops for hybrid fleets; 4 good; 3 faster

**Comment by k-doering-NOAA** [comment]
Ok, if vermillion snapper is the one, I think we should add a second version of the model, since vermillion is our only F method 2 model. Thanks for pasting in the setup!
