### ISSUE TITLE
update hake

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/ss-test-models#3]
@Rick-Methot-NOAA realized hake didn't have a pos def hessian; this is b/c some std error vals requested didn't have any se . Remove these values form the testing model. See if this happens in other models

**Comment by iantaylor-NOAA** [comment]
I'm confused by the need for this change. I get the idea, but for this specific model the requested extra stddev reporting was for selectivity uncertainty and numbers at age, but not growth (because it's an empirical weight-at-age model), as shown in the better-formatted entries from control.ss_new below (from before the recent commits).

Perhaps the issue is that age-1 selectivity for fleet 2 is fixed at 0. @k-doering-NOAA, could you try either changing the selectivity to fleet 1 or removing the age-1 bin to see if that fixes the problem? Keeping these extra stddev outputs within at least one of the test models seems useful.

```
1 # (0/1/2) read specs for more stddev reporting: 0 = skip, 1 = read specs for reporting stdev for selectivity, size, and numbers, 2 = add options for M and Dyn Bzero
 2 2 -1 15 # Selectivity: (1) 0 to skip or fleet, (2) 1=len/2=age/3=combined, (3) year, (4) N selex bins; NOTE: combined reports in age bins
 0 0 # Growth: (1) 0 to skip or growth pattern, (2) growth ages; NOTE: does each sex
 1 -1 1 # Numbers-at-age: (1) 0 or area(-1 for all), (2) year, (3) N ages;  NOTE: sums across morphs
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 # vector with selex std bins (-1 in first bin to self-generate)
 # -1 # list of ages for growth std (-1 in first bin to self-generate)
 20 # vector with NatAge std ages (-1 in first bin to self-generate)
```

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA, for the comments. I saw ~ 3 other models (including simple) were using the std dev reporting already, so that's why I thought it was ok to just delete this output from the hake examples altogether - but this was because I didn't know exactly which output was causing the probem!

Now that I know, I can add it back in (maybe just in 1 of the version of hake?). Thanks for speaking up.

**Comment by Rick-Methot-NOAA** [comment]
this worked for me:
1 # (0/1/2) read specs for more stddev reporting: 0 = skip, 1 = read specs
for reporting stdev for selectivity, size, and numbers, 2 = add options for
M and Dyn Bzero
 2 2 -1 4 # Selectivity: (1) 0 to skip or fleet, (2)
1=len/2=age/3=combined, (3) year, (4) N selex bins; NOTE: combined reports
in age bins
 0 0 # Growth: (1) 0 to skip or growth pattern, (2) growth ages; NOTE: does
each sex
 1 -1 1 # Numbers-at-age: (1) 0 or area(-1 for all), (2) year, (3) N ages;
 NOTE: sums across morphs
 2 3 4 5 # vector with selex std bins (-1 in first bin to self-generate)
 # -1 # list of ages for growth std (-1 in first bin to self-generate)
 20 # vector with NatAge std ages (-1 in first bin to self-generate)

**Comment by iantaylor-NOAA** [comment]
Thanks @Rick-Methot-NOAA and @k-doering-NOAA. Adding Rick's input with reduced selectivity bins one of the two hake models makes sense to me.

Somewhat off-topic, but it might be a good idea to include in ss-test-models an example with Lorenzen M if we don't already have it, which could then use the "add options" extra stddev reporting as discussed in this VLab issue: https://vlab.ncep.noaa.gov/redmine/issues/72659.

**Comment by k-doering-NOAA** [comment]
Commit cbc12a7 adds back some stdev quantities back in, and it appears there is a positive definite hessian.
