### ISSUE TITLE
Lorenzen M model with std error options

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/ss-test-models#5]
Somewhat off-topic, but it might be a good idea to include in ss-test-models an example with Lorenzen M if we don't already have it, which could then use the "add options" extra stddev reporting as discussed in this VLab issue: https://vlab.ncep.noaa.gov/redmine/issues/72659.

_Originally posted by @iantaylor-NOAA in https://github.com/nmfs-stock-synthesis/ss-test-models/issues/3#issuecomment-816932258_

**Comment by k-doering-NOAA** [comment]
@iantaylor-NOAA I opened a new issue for this so it doesn't get lost. I checked our test set and we don't have a model that uses Lorenzen M and I think we should. Do you have a model you could add? I think I have a version of Simple, but I think a completely different model would be better.

**Comment by iantaylor-NOAA** [comment]
Simple_Lorenzen added in commit 6c7d485 and refined in commit b9694dab25346e39572248895f3beaafc9bf1c0f. Changes (which could be applied automatically as suggested in #2) are switching M type to Lorenzen adding extra stddev input to get uncertainty in M-at-age, and adding lambda = 0 for mean lenght-at-age data and lambda = 0.1 for length comps to increase the uncertainty in growth and make the resulting uncertainty in M more perceptible, although it's still pretty small (see r4ss plot below).

Note: this model also includes the uncertainty in dynamic B0 which @Rick-Methot-NOAA added in May (see change [here](https://github.com/nmfs-stock-synthesis/stock-synthesis/commit/889a2503206124e1b0bca27820364100c09e5ac1#diff-3e180413942d2bc605d2a2fb46edeaee38f05110ea63eca4cc12c4767e1b3cfeL3947-R3973)), but isn't yet described in the User Manual. I'll post a separate issue about that.

![image](https://user-images.githubusercontent.com/4992918/114241353-dcb77f00-993d-11eb-85ad-a53f11b5fffb.png)

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA ! I added this model to the table on the readme and also updated to the ss.par file (because there was recently a [breaking change in par files in ss] (see https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/135#issuecomment-800623554) . Tested on jenkins with no estimation and the model ran and no changes were found.
