### ISSUE TITLE
modify starting values for vermillion snapper?

### ISSUE THREAD

**Issue by k-doering-NOAA** [nmfs-stock-synthesis/ss-test-models#8]
While creating a new job to run SS on some of the fast running models with estimation using github actions (see https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/170), the new github runner found a better solution for vermillion snapper: 359.902 vs 366.379 NLL. I ran 10 models while jittering the starting values on my local windows machine and found that this lower likelihood is indeed found:
```
Table of likelihood values:
likesaved
359.902 366.379 381.483  387.79 408.898 422.094 
      5       1       1       1       1       1 
```

This suggests that the vermillion model is sensitive to starting values. 

Perhaps a solution to continue to use this model in testing is to update the starting values to match one of the runs where 359 was the found likelihood? Or we could try to change the model to reduce its sensitivity to starting values.  I think we want to retain this model as it is currently our only model using F method 2 in the test set.

@Rick-Methot-NOAA and @iantaylor-NOAA , do you have thoughts on what to do about this?

**Comment by iantaylor-NOAA** [comment]
Using control.ss_new associated with best fit seems reasonable to me. Any changes to SS which impact the results should still be visible even with starting from the MLE, so the model would still be useful for testing. However, if there's an easy way to change the model to make it more stable, that could be done too.

**Comment by k-doering-NOAA** [comment]
While updating this model, I noticed that the reference files had actually been updated previously to the higher NLL: https://github.com/nmfs-stock-synthesis/ss-test-models/commit/811584fd916570a61ceefdbd3e1d191b3ef9a0a9#diff-852842ff3a43bbad9121f9bbebfa8773cea3735bbfd0279c6eb8d301a28dc66c

I think this was to get the job to stop failing the jenkins runs without too much effort. I should have realized at this point that the model was sensitive to starting values/ the machine it was run on! 

Testing the new output files with gh actions to see if the run-with-est job stops flagging vermillion as failing. If looks good, then I will close this issue (though we can revisit if we decide to look more into the model structure causing the sensitivity to starting values)

**Comment by k-doering-NOAA** [comment]
Well, that didn't work. When starting from the MLE with the lower likelihood, github actions is finding a higher likelihood for some reason. Looks like trying to make the model less sensitive to starting value will be necessary.

**Comment by k-doering-NOAA** [comment]
There are 2 double normal selectivity curves in the model where all parameters are estimated. Fixing half of these parameters at the MLE value seems to make the model less sensitve to starting value (I ran 10 jitters, and only 1 found a different solution than the lowest NLL).

So now, the starting values are at the MLE with some selectivity variable fixed. Would it be worth exploring if just fixing more selectivity values with the original model starting values solves the issue?

**Comment by k-doering-NOAA** [comment]
I will leave this as-is for now (using starting values from MLE, with additional fixed sel params). We can always modify in the future.   both jenkins and the github actions run-with-est are now passing, including for vermillion, so our goal for now has been accomplished.
